---
title: "Final Project"
subtitle: "Data Exploration"
author: ""
date: "2019-Feb-25"
fontsize: 8 pt
output:
  #    beamer_presentation: #everything after hash "#" will be ignored 
pdf_document:
number_sections: false
fig_width: 6
fig_height: 4
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      #include = TRUE, 
                      eval = TRUE, 
                      
                      fig.width = 6, fig.height = 4,
                      results='hold',
                      warning = FALSE,
                      message=FALSE,
                      cache = TRUE,
                      digits = 3) 
```

```{r,echo=FALSE,results='hide', message=FALSE}
# Packages and Data Parser
#Note: Be sure plyr is loaded before dplyr
PackageList =c("plyr","dplyr","tidyverse","lubridate","censusapi","forcats","lemon")
NewPackages=PackageList[!(PackageList %in% 
                            installed.packages()[,"Package"])]
if(length(NewPackages)) install.packages(NewPackages,repos = "http://cran.us.r-project.org")
lapply(PackageList,require,character.only=TRUE)#array function

options(tibble.print_max = Inf, tibble.print_min = 20) 
set.seed(1) #Always set the seed for reproducibility

knit_print.data.frame <- lemon_print
```

Load data and begin generating exploratory plots.

```{r }
source("taxiData.R")
#Load records from taxi data source and store as a dataframe
data1m <- taxiData(5000000)
df <- data.frame(data1m$rawData)
rm(data1m) #Drop old data
df$dropoff_community_area<-as.factor(df$dropoff_community_area)
df$dropoff_centroid_location.coordinates<-as.character(df$dropoff_centroid_location.coordinates)
df$pickup_centroid_location.coordinates<-as.character(df$pickup_centroid_location.coordinates)
df$trip_total<-as.numeric(df$trip_total)

#Select only the columns we will be using
colKeep<-c("company","pickup_community_area","dropoff_community_area","fare","tolls","extras","tips","payment_type","taxi_id","trip_miles","trip_seconds","trip_end_timestamp","trip_start_timestamp","trip_total","pickup_census_tract","dropoff_census_tract")
df<-df[, (names(df) %in% colKeep)]
```
We need to compute some base stats for our initial dataset. 

```{r caption="Data frame is now printed using `kable`.",render=lemon_print}

knit_print.data.frame <- lemon_print
#% of Records that are NA in each column
summaryNA <- as.data.frame(sapply(df,function(x) sum(is.na(x)))/nrow(df)*100)
#% of records that are zero in each column
summaryZero <- as.data.frame(colSums(df==0,na.rm=TRUE)/nrow(df)*100)

#Drop all NA records for the following columns
naFilter<-c("fare","tolls","extras","tips","trip_total","trip_seconds","trip_miles","trip_end_timestamp","dropoff_community_area","pickup_community_area")

dfClean<-df[complete.cases(df[,naFilter]),]

#Drop records where miles, seconds, fare <=0
dfClean<-dfClean[dfClean$trip_miles>0,]
dfClean<-dfClean[dfClean$trip_seconds>0,]
dfClean<-dfClean[dfClean$fare>0,]

cat("After dropping NA and zero records: ", round(100*(1-(nrow(dfClean)/nrow(df))),1),"% of records dropped")
```



```{r}
#Load census data by Chicago Community Area
ccaData <- read.csv("ChicagoCCAData.csv")
ccaData$CCA.Code<-as.factor(ccaData$CCA.Code)
ccaData$GEOG<-as.factor(ccaData$GEOG)
#Look up name of pickup CCA and add to df
df<- df %>% left_join(select(ccaData,GEOG,CCA.Code),by=c("pickup_community_area"="CCA.Code"))
names(df)[names(df) == 'GEOG'] <- 'pickup_area'
#Look up name of dropoff CCA and add to df
df<- df %>% left_join(select(ccaData,GEOG,CCA.Code),by=c("dropoff_community_area"="CCA.Code"))
names(df)[names(df) == 'GEOG'] <- 'dropoff_area'
#Look up population>16yo of pickup CCA and add to df
df<- df %>% left_join(select(ccaData,POP_16OV,CCA.Code),by=c("pickup_community_area"="CCA.Code"))
names(df)[names(df) == 'POP_16OV'] <- 'Pop16Plus'
#Look up Labor Force of pickup CCA and add to df
df<- df %>% left_join(select(ccaData,IN_LBFRC,CCA.Code),by=c("pickup_community_area"="CCA.Code"))
names(df)[names(df) == 'IN_LBFRC'] <- 'IN_LBFRC'
#Look up Unemp of pickup CCA and add to df
df<- df %>% left_join(select(ccaData,UNEMP,CCA.Code),by=c("pickup_community_area"="CCA.Code"))
names(df)[names(df) == 'UNEMP'] <- 'UNEMP'
#Look up Unemp of pickup CCA and add to df
df<- df %>% left_join(select(ccaData,MEDINC,CCA.Code),by=c("pickup_community_area"="CCA.Code"))
names(df)[names(df) == 'MEDINC'] <- 'MedIncome'
```



```{r}
df$company[df$company=="Chicago Elite Cab Corp. (Chicago Carriag"] <- "Chicago Elite Cab Corp."
df$startDate <- date(df$trip_start_timestamp)
df$endDate <- date(df$trip_end_timestamp)
df$endDay <- wday(df$trip_end_timestamp,label=TRUE)
df$endMonth <- month(df$trip_end_timestamp,label=TRUE)
df$endHour <- hour(str_replace(df$trip_end_timestamp,"T"," "))
```

Throw out all rows where fare, duration, or distance=0 and where NAs exist for dropoff/pickup location and convert NA to explicit for company (necessary in summary calcs)

```{r}
#Uncomment the following line to drop all records where dropoff_area and pickup_area NA
#df<-df %>% drop_na(c("dropoff_area","pickup_area"))
#Replace <NA> with string "NA" which can be used for grouping
nrowPreFilter=nrow(df)
df <- df[df$fare>0,]
df <- df[df$trip_miles>0,]
df <- df[df$trip_seconds>0,]
df <- df[df$trip_total>0,]
df$company <- fct_explicit_na(df$company,"NA")

cat("Filtering out records where fare,trip_miles,trip_seconds=0. Remaining records: ", round(100*nrow(df)/nrowPreFilter,1),"% of data. Leaves ", nrow(df)," total records.")
```

