---
title: "Final Project"
subtitle: "Data Exploration"
author: ""
date: "2019-Feb-25"
fontsize: 8 pt
output:
  #    beamer_presentation: #everything after hash "#" will be ignored 
pdf_document:
number_sections: false
fig_width: 6
fig_height: 4
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      #include = TRUE, 
                      eval = TRUE, 
                      
                      fig.width = 6, fig.height = 4,
                      results='hold',
                      warning = FALSE,
                      message=FALSE,
                      cache = TRUE,
                      digits = 3) 
```

```{r,echo=FALSE,results='hide', message=FALSE}
# Packages and Data Parser
#Note: Be sure plyr is loaded before dplyr
PackageList =c("plyr","dplyr","tidyverse","lubridate","censusapi","forcats")
NewPackages=PackageList[!(PackageList %in% 
                            installed.packages()[,"Package"])]
if(length(NewPackages)) install.packages(NewPackages,repos = "http://cran.us.r-project.org")
lapply(PackageList,require,character.only=TRUE)#array function

options(tibble.print_max = Inf, tibble.print_min = 20) 
set.seed(1) #Always set the seed for reproducibility
```

Load data and begin generating exploratory plots.

```{r}
source("taxiData.R")
#Load records from taxi data
data1m <- taxiData(100000)
data1mDF <- data.frame(data1m$rawData)
#Replace <NA> with string "NA" which can be used for grouping


data1mDF$dropoff_community_area<-as.factor(data1mDF$dropoff_community_area)
#Load census data by Chicago Community Area
ccaData <- read.csv("ChicagoCCAData.csv")
ccaData$CCA.Code<-as.factor(ccaData$CCA.Code)
ccaData$GEOG<-as.factor(ccaData$GEOG)
#Lookup name of pickup CCA and add
df<- data1mDF %>% left_join(select(ccaData,GEOG,CCA.Code),by=c("pickup_community_area"="CCA.Code"))
names(df)[names(df) == 'GEOG'] <- 'pickup_area'
#Lookup name of dropoff CCA and add
df<- df %>% left_join(select(ccaData,GEOG,CCA.Code),by=c("dropoff_community_area"="CCA.Code"))
names(df)[names(df) == 'GEOG'] <- 'dropoff_area'

df$dropoff_area <- fct_explicit_na(df$dropoff_area,"NA")
df$pickup_area <- fct_explicit_na(df$pickup_area,"NA")
df$company <- fct_explicit_na(df$company,"NA")
```

Clean data. For instance, "Chicago Elite Cab Corp. (Chicago Carriag" and "Chicago Elite Cab Corp." are clearly the same firm. We replace the former with the latter. 
We add factors for the Start Date (as opposed to date time), End Date, and Start Day of Week.
```{r}
df$company[data1mDF$company=="Chicago Elite Cab Corp. (Chicago Carriag"] <- "Chicago Elite Cab Corp."
df$startDate<-date(data1mDF$trip_start_timestamp)
df$endDate<-date(data1mDF$trip_end_timestamp)
df$endDay<-wday(data1mDF$trip_end_timestamp,label=TRUE)
```

## Start Summary Tables
```{r}
#Note: I am calling dplyr's functions directly to avoid issues with summarize
#Trips by Company
df %>% dplyr::group_by(company) %>% tally(sort=TRUE)
#Trips by Dropoff Area
df %>% dplyr::group_by(dropoff_area) %>% tally(sort=TRUE)
#Trips by Origination and Destination
df %>% dplyr::group_by(pickup_area,dropoff_area) %>% tally(sort=TRUE)
#Trips by Pickup Area
df %>% dplyr::group_by(pickup_area) %>% tally(sort=TRUE)
#Avg Fare and Distance by Pickup Area
df %>% dplyr::group_by(pickup_area) %>% dplyr::summarize(total_trips=n(),mean_fare = round(mean(fare,na.rm=TRUE),2),mean_distance=round(mean(trip_miles,na.rm=TRUE),1))
#Avg Fare and Distance by Dropoff Area
df %>% dplyr::group_by(dropoff_area) %>% dplyr::summarize(total_trips=n(),mean_fare = round(mean(fare,na.rm=TRUE),2),mean_distance=round(mean(trip_miles,na.rm=TRUE),1))
#Avg Fare and Distance by Pickup and Dropoff Areas
df %>% dplyr::group_by(pickup_area,dropoff_area) %>% dplyr::summarize(total_trips=n(),mean_fare = round(mean(fare,na.rm=TRUE),2),mean_distance=round(mean(trip_miles,na.rm=TRUE),1))
```



Add column for date
```{r}

data1mDF %>% group_by(month=floor_date(trip_start_timestamp, "month")) %>%
   summarize(amount=sum(fare))
```




```{r}

ggplot(data = data1mDF) +
  geom_histogram(mapping = aes(x = fare), binwidth = 5)

ggplot(data = data1mDF) +
  geom_bar(mapping = aes(x = company))

ggplot(data = data1mDF) +
  geom_bar(mapping = aes(x = company))

ggplot(data = data1mDF, aes(x = trip_start_timestamp)) + 
 geom_density(fill = "blue")

```

```{r}
orderedFares<-data1mDF$fare[order(data1mDF$fare,decreasing = TRUE)]

boxplot(orderedFares[10:length(orderedFares)])
```

